'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="CL")>  _
Partial Public Class ComDataDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "擴充性方法定義"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub Inserttbl_Access(instance As tbl_Access)
    End Sub
  Partial Private Sub Updatetbl_Access(instance As tbl_Access)
    End Sub
  Partial Private Sub Deletetbl_Access(instance As tbl_Access)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.Companion.My.MySettings.Default.CLConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property tbl_Access() As System.Data.Linq.Table(Of tbl_Access)
		Get
			Return Me.GetTable(Of tbl_Access)
		End Get
	End Property
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_insert_access")>  _
	Public Function sp_insert_access(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="SDATE", DbType:="Date")> ByVal sDATE As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="VIST", DbType:="NVarChar(50)")> ByVal vIST As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="RMNO", DbType:="TinyInt")> ByVal rMNO As System.Nullable(Of Byte), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Nr", DbType:="TinyInt")> ByVal nr As System.Nullable(Of Byte), <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal uid As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal cname As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="STATUS", DbType:="Bit")> ByVal sTATUS As System.Nullable(Of Boolean)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), sDATE, vIST, rMNO, nr, uid, cname, sTATUS)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_labdata_by_uid")>  _
	Public Function sp_labdata_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_labdata_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_labdata_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_labdata_CBC_by_uid")>  _
	Public Function sp_labdata_CBC_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_labdata_CBC_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_labdata_CBC_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_labdata_DM_by_uid")>  _
	Public Function sp_labdata_DM_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_labdata_DM_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_labdata_DM_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_labdata_DRUG_by_uid")>  _
	Public Function sp_labdata_DRUG_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_labdata_DRUG_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_labdata_DRUG_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_labdata_hepa_by_uid")>  _
	Public Function sp_labdata_hepa_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_labdata_hepa_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_labdata_hepa_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_labdata_OTHER_by_uid")>  _
	Public Function sp_labdata_OTHER_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_labdata_OTHER_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_labdata_OTHER_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_labdata_UA_by_uid")>  _
	Public Function sp_labdata_UA_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_labdata_UA_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_labdata_UA_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_cloudlab_by_uid")>  _
	Public Function sp_cloudlab_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_cloudlab_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_cloudlab_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_cloudmed_by_uid")>  _
	Public Function sp_cloudmed_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_cloudmed_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_cloudmed_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_querytable")>  _
	Public Function sp_querytable() As ISingleResult(Of sp_querytableResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of sp_querytableResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_cloudDEN_by_uid")>  _
	Public Function sp_cloudDEN_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_cloudDEN_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_cloudDEN_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_cloudOP_by_uid")>  _
	Public Function sp_cloudOP_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_cloudOP_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_cloudOP_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_cloudTCM_by_uid")>  _
	Public Function sp_cloudTCM_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_cloudTCM_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_cloudTCM_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_cloudREH_by_uid")>  _
	Public Function sp_cloudREH_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_cloudREH_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_cloudREH_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_cloudDIS_by_uid")>  _
	Public Function sp_cloudDIS_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_cloudDIS_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_cloudDIS_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_cloudALL_by_uid")>  _
	Public Function sp_cloudALL_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_cloudALL_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_cloudALL_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_cloudSCH_R_by_uid")>  _
	Public Function sp_cloudSCH_R_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_cloudSCH_R_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_cloudSCH_R_by_uidResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_cloudSCH_U_by_uid")>  _
	Public Function sp_cloudSCH_U_by_uid(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(50)")> ByVal u As String) As ISingleResult(Of sp_cloudSCH_U_by_uidResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), u)
		Return CType(result.ReturnValue,ISingleResult(Of sp_cloudSCH_U_by_uidResult))
	End Function
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tbl_Access")>  _
Partial Public Class tbl_Access
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _Access_id As Long
	
	Private _SDATE As Date
	
	Private _VIST As String
	
	Private _RMNO As Byte
	
	Private _Nr As Byte
	
	Private _uid As String
	
	Private _cname As String
	
	Private _STATUS As Boolean
	
	Private _access_time As Date
	
    #Region "擴充性方法定義"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnAccess_idChanging(value As Long)
    End Sub
    Partial Private Sub OnAccess_idChanged()
    End Sub
    Partial Private Sub OnSDATEChanging(value As Date)
    End Sub
    Partial Private Sub OnSDATEChanged()
    End Sub
    Partial Private Sub OnVISTChanging(value As String)
    End Sub
    Partial Private Sub OnVISTChanged()
    End Sub
    Partial Private Sub OnRMNOChanging(value As Byte)
    End Sub
    Partial Private Sub OnRMNOChanged()
    End Sub
    Partial Private Sub OnNrChanging(value As Byte)
    End Sub
    Partial Private Sub OnNrChanged()
    End Sub
    Partial Private Sub OnuidChanging(value As String)
    End Sub
    Partial Private Sub OnuidChanged()
    End Sub
    Partial Private Sub OncnameChanging(value As String)
    End Sub
    Partial Private Sub OncnameChanged()
    End Sub
    Partial Private Sub OnSTATUSChanging(value As Boolean)
    End Sub
    Partial Private Sub OnSTATUSChanged()
    End Sub
    Partial Private Sub Onaccess_timeChanging(value As Date)
    End Sub
    Partial Private Sub Onaccess_timeChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Access_id", AutoSync:=AutoSync.OnInsert, DbType:="BigInt NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property Access_id() As Long
		Get
			Return Me._Access_id
		End Get
		Set
			If ((Me._Access_id = value)  _
						= false) Then
				Me.OnAccess_idChanging(value)
				Me.SendPropertyChanging
				Me._Access_id = value
				Me.SendPropertyChanged("Access_id")
				Me.OnAccess_idChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date NOT NULL")>  _
	Public Property SDATE() As Date
		Get
			Return Me._SDATE
		End Get
		Set
			If ((Me._SDATE = value)  _
						= false) Then
				Me.OnSDATEChanging(value)
				Me.SendPropertyChanging
				Me._SDATE = value
				Me.SendPropertyChanged("SDATE")
				Me.OnSDATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VIST", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property VIST() As String
		Get
			Return Me._VIST
		End Get
		Set
			If (String.Equals(Me._VIST, value) = false) Then
				Me.OnVISTChanging(value)
				Me.SendPropertyChanging
				Me._VIST = value
				Me.SendPropertyChanged("VIST")
				Me.OnVISTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RMNO", DbType:="TinyInt NOT NULL")>  _
	Public Property RMNO() As Byte
		Get
			Return Me._RMNO
		End Get
		Set
			If ((Me._RMNO = value)  _
						= false) Then
				Me.OnRMNOChanging(value)
				Me.SendPropertyChanging
				Me._RMNO = value
				Me.SendPropertyChanged("RMNO")
				Me.OnRMNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Nr", DbType:="TinyInt NOT NULL")>  _
	Public Property Nr() As Byte
		Get
			Return Me._Nr
		End Get
		Set
			If ((Me._Nr = value)  _
						= false) Then
				Me.OnNrChanging(value)
				Me.SendPropertyChanging
				Me._Nr = value
				Me.SendPropertyChanged("Nr")
				Me.OnNrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_uid", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property uid() As String
		Get
			Return Me._uid
		End Get
		Set
			If (String.Equals(Me._uid, value) = false) Then
				Me.OnuidChanging(value)
				Me.SendPropertyChanging
				Me._uid = value
				Me.SendPropertyChanged("uid")
				Me.OnuidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cname", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property cname() As String
		Get
			Return Me._cname
		End Get
		Set
			If (String.Equals(Me._cname, value) = false) Then
				Me.OncnameChanging(value)
				Me.SendPropertyChanging
				Me._cname = value
				Me.SendPropertyChanged("cname")
				Me.OncnameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STATUS", DbType:="Bit NOT NULL")>  _
	Public Property STATUS() As Boolean
		Get
			Return Me._STATUS
		End Get
		Set
			If ((Me._STATUS = value)  _
						= false) Then
				Me.OnSTATUSChanging(value)
				Me.SendPropertyChanging
				Me._STATUS = value
				Me.SendPropertyChanged("STATUS")
				Me.OnSTATUSChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_access_time", DbType:="DateTime NOT NULL")>  _
	Public Property access_time() As Date
		Get
			Return Me._access_time
		End Get
		Set
			If ((Me._access_time = value)  _
						= false) Then
				Me.Onaccess_timeChanging(value)
				Me.SendPropertyChanging
				Me._access_time = value
				Me.SendPropertyChanged("access_time")
				Me.Onaccess_timeChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

Partial Public Class sp_labdata_by_uidResult
	
	Private _SDATE As System.Nullable(Of Date)
	
	Private _o As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date")>  _
	Public Property SDATE() As System.Nullable(Of Date)
		Get
			Return Me._SDATE
		End Get
		Set
			If (Me._SDATE.Equals(value) = false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_o", DbType:="NVarChar(3999)")>  _
	Public Property o() As String
		Get
			Return Me._o
		End Get
		Set
			If (String.Equals(Me._o, value) = false) Then
				Me._o = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_labdata_CBC_by_uidResult
	
	Private _SDATE As System.Nullable(Of Date)
	
	Private _o As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date")>  _
	Public Property SDATE() As System.Nullable(Of Date)
		Get
			Return Me._SDATE
		End Get
		Set
			If (Me._SDATE.Equals(value) = false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_o", DbType:="NVarChar(3999)")>  _
	Public Property o() As String
		Get
			Return Me._o
		End Get
		Set
			If (String.Equals(Me._o, value) = false) Then
				Me._o = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_labdata_DM_by_uidResult
	
	Private _SDATE As System.Nullable(Of Date)
	
	Private _o As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date")>  _
	Public Property SDATE() As System.Nullable(Of Date)
		Get
			Return Me._SDATE
		End Get
		Set
			If (Me._SDATE.Equals(value) = false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_o", DbType:="NVarChar(3999)")>  _
	Public Property o() As String
		Get
			Return Me._o
		End Get
		Set
			If (String.Equals(Me._o, value) = false) Then
				Me._o = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_labdata_DRUG_by_uidResult
	
	Private _SDATE As System.Nullable(Of Date)
	
	Private _o As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date")>  _
	Public Property SDATE() As System.Nullable(Of Date)
		Get
			Return Me._SDATE
		End Get
		Set
			If (Me._SDATE.Equals(value) = false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_o", DbType:="NVarChar(3999)")>  _
	Public Property o() As String
		Get
			Return Me._o
		End Get
		Set
			If (String.Equals(Me._o, value) = false) Then
				Me._o = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_labdata_hepa_by_uidResult
	
	Private _SDATE As System.Nullable(Of Date)
	
	Private _o As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date")>  _
	Public Property SDATE() As System.Nullable(Of Date)
		Get
			Return Me._SDATE
		End Get
		Set
			If (Me._SDATE.Equals(value) = false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_o", DbType:="NVarChar(3999)")>  _
	Public Property o() As String
		Get
			Return Me._o
		End Get
		Set
			If (String.Equals(Me._o, value) = false) Then
				Me._o = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_labdata_OTHER_by_uidResult
	
	Private _SDATE As System.Nullable(Of Date)
	
	Private _o As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date")>  _
	Public Property SDATE() As System.Nullable(Of Date)
		Get
			Return Me._SDATE
		End Get
		Set
			If (Me._SDATE.Equals(value) = false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_o", DbType:="NVarChar(3999)")>  _
	Public Property o() As String
		Get
			Return Me._o
		End Get
		Set
			If (String.Equals(Me._o, value) = false) Then
				Me._o = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_labdata_UA_by_uidResult
	
	Private _SDATE As System.Nullable(Of Date)
	
	Private _o As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date")>  _
	Public Property SDATE() As System.Nullable(Of Date)
		Get
			Return Me._SDATE
		End Get
		Set
			If (Me._SDATE.Equals(value) = false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_o", DbType:="NVarChar(3999)")>  _
	Public Property o() As String
		Get
			Return Me._o
		End Get
		Set
			If (String.Equals(Me._o, value) = false) Then
				Me._o = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_cloudlab_by_uidResult
	
	Private _SDATE As System.Nullable(Of Date)
	
	Private _source As String
	
	Private _o As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date")>  _
	Public Property SDATE() As System.Nullable(Of Date)
		Get
			Return Me._SDATE
		End Get
		Set
			If (Me._SDATE.Equals(value) = false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_source", DbType:="NVarChar(10)")>  _
	Public Property source() As String
		Get
			Return Me._source
		End Get
		Set
			If (String.Equals(Me._source, value) = false) Then
				Me._source = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_o", DbType:="NVarChar(3999)")>  _
	Public Property o() As String
		Get
			Return Me._o
		End Get
		Set
			If (String.Equals(Me._o, value) = false) Then
				Me._o = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_cloudmed_by_uidResult
	
	Private _SDATE As System.Nullable(Of Date)
	
	Private _source As String
	
	Private _diag As String
	
	Private _o As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date")>  _
	Public Property SDATE() As System.Nullable(Of Date)
		Get
			Return Me._SDATE
		End Get
		Set
			If (Me._SDATE.Equals(value) = false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_source", DbType:="NVarChar(10)")>  _
	Public Property source() As String
		Get
			Return Me._source
		End Get
		Set
			If (String.Equals(Me._source, value) = false) Then
				Me._source = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_diag", DbType:="NVarChar(500)")>  _
	Public Property diag() As String
		Get
			Return Me._diag
		End Get
		Set
			If (String.Equals(Me._diag, value) = false) Then
				Me._diag = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_o", DbType:="NVarChar(3999)")>  _
	Public Property o() As String
		Get
			Return Me._o
		End Get
		Set
			If (String.Equals(Me._o, value) = false) Then
				Me._o = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_querytableResult
	
	Private _Query_id As Long
	
	Private _uid As String
	
	Private _QDATE As System.Nullable(Of Date)
	
	Private _if_cloudmed As System.Nullable(Of Boolean)
	
	Private _if_schedule As System.Nullable(Of Boolean)
	
	Private _if_cloudlab As System.Nullable(Of Boolean)
	
	Private _cname As String
	
	Private _OP As System.Nullable(Of Boolean)
	
	Private _discharge As System.Nullable(Of Boolean)
	
	Private _rehab As System.Nullable(Of Boolean)
	
	Private _if_TCM As System.Nullable(Of Boolean)
	
	Private _if_dental As System.Nullable(Of Boolean)
	
	Private _if_allergy As System.Nullable(Of Boolean)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Query_id", DbType:="BigInt NOT NULL")>  _
	Public Property Query_id() As Long
		Get
			Return Me._Query_id
		End Get
		Set
			If ((Me._Query_id = value)  _
						= false) Then
				Me._Query_id = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_uid", DbType:="NVarChar(20)")>  _
	Public Property uid() As String
		Get
			Return Me._uid
		End Get
		Set
			If (String.Equals(Me._uid, value) = false) Then
				Me._uid = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_QDATE", DbType:="DateTime")>  _
	Public Property QDATE() As System.Nullable(Of Date)
		Get
			Return Me._QDATE
		End Get
		Set
			If (Me._QDATE.Equals(value) = false) Then
				Me._QDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_if_cloudmed", DbType:="Bit")>  _
	Public Property if_cloudmed() As System.Nullable(Of Boolean)
		Get
			Return Me._if_cloudmed
		End Get
		Set
			If (Me._if_cloudmed.Equals(value) = false) Then
				Me._if_cloudmed = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_if_schedule", DbType:="Bit")>  _
	Public Property if_schedule() As System.Nullable(Of Boolean)
		Get
			Return Me._if_schedule
		End Get
		Set
			If (Me._if_schedule.Equals(value) = false) Then
				Me._if_schedule = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_if_cloudlab", DbType:="Bit")>  _
	Public Property if_cloudlab() As System.Nullable(Of Boolean)
		Get
			Return Me._if_cloudlab
		End Get
		Set
			If (Me._if_cloudlab.Equals(value) = false) Then
				Me._if_cloudlab = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cname", DbType:="NVarChar(50)")>  _
	Public Property cname() As String
		Get
			Return Me._cname
		End Get
		Set
			If (String.Equals(Me._cname, value) = false) Then
				Me._cname = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OP", DbType:="Bit")>  _
	Public Property OP() As System.Nullable(Of Boolean)
		Get
			Return Me._OP
		End Get
		Set
			If (Me._OP.Equals(value) = false) Then
				Me._OP = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_discharge", DbType:="Bit")>  _
	Public Property discharge() As System.Nullable(Of Boolean)
		Get
			Return Me._discharge
		End Get
		Set
			If (Me._discharge.Equals(value) = false) Then
				Me._discharge = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rehab", DbType:="Bit")>  _
	Public Property rehab() As System.Nullable(Of Boolean)
		Get
			Return Me._rehab
		End Get
		Set
			If (Me._rehab.Equals(value) = false) Then
				Me._rehab = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_if_TCM", DbType:="Bit")>  _
	Public Property if_TCM() As System.Nullable(Of Boolean)
		Get
			Return Me._if_TCM
		End Get
		Set
			If (Me._if_TCM.Equals(value) = false) Then
				Me._if_TCM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_if_dental", DbType:="Bit")>  _
	Public Property if_dental() As System.Nullable(Of Boolean)
		Get
			Return Me._if_dental
		End Get
		Set
			If (Me._if_dental.Equals(value) = false) Then
				Me._if_dental = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_if_allergy", DbType:="Bit")>  _
	Public Property if_allergy() As System.Nullable(Of Boolean)
		Get
			Return Me._if_allergy
		End Get
		Set
			If (Me._if_allergy.Equals(value) = false) Then
				Me._if_allergy = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_cloudDEN_by_uidResult
	
	Private _SDATE As Date
	
	Private _source_name As String
	
	Private _diagnosis As String
	
	Private _op_name As String
	
	Private _loca As String
	
	Private _amt As System.Nullable(Of Byte)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date NOT NULL")>  _
	Public Property SDATE() As Date
		Get
			Return Me._SDATE
		End Get
		Set
			If ((Me._SDATE = value)  _
						= false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_source_name", DbType:="NVarChar(100)")>  _
	Public Property source_name() As String
		Get
			Return Me._source_name
		End Get
		Set
			If (String.Equals(Me._source_name, value) = false) Then
				Me._source_name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_diagnosis", DbType:="NVarChar(50)")>  _
	Public Property diagnosis() As String
		Get
			Return Me._diagnosis
		End Get
		Set
			If (String.Equals(Me._diagnosis, value) = false) Then
				Me._diagnosis = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_op_name", DbType:="NVarChar(100)")>  _
	Public Property op_name() As String
		Get
			Return Me._op_name
		End Get
		Set
			If (String.Equals(Me._op_name, value) = false) Then
				Me._op_name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_loca", DbType:="NVarChar(50)")>  _
	Public Property loca() As String
		Get
			Return Me._loca
		End Get
		Set
			If (String.Equals(Me._loca, value) = false) Then
				Me._loca = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_amt", DbType:="TinyInt")>  _
	Public Property amt() As System.Nullable(Of Byte)
		Get
			Return Me._amt
		End Get
		Set
			If (Me._amt.Equals(value) = false) Then
				Me._amt = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_cloudOP_by_uidResult
	
	Private _SDATE As Date
	
	Private _source_name As String
	
	Private _dep As String
	
	Private _diagnosis As String
	
	Private _op_name As String
	
	Private _loca As String
	
	Private _amt As System.Nullable(Of Byte)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date NOT NULL")>  _
	Public Property SDATE() As Date
		Get
			Return Me._SDATE
		End Get
		Set
			If ((Me._SDATE = value)  _
						= false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_source_name", DbType:="NVarChar(100)")>  _
	Public Property source_name() As String
		Get
			Return Me._source_name
		End Get
		Set
			If (String.Equals(Me._source_name, value) = false) Then
				Me._source_name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dep", DbType:="NVarChar(50)")>  _
	Public Property dep() As String
		Get
			Return Me._dep
		End Get
		Set
			If (String.Equals(Me._dep, value) = false) Then
				Me._dep = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_diagnosis", DbType:="NVarChar(50)")>  _
	Public Property diagnosis() As String
		Get
			Return Me._diagnosis
		End Get
		Set
			If (String.Equals(Me._diagnosis, value) = false) Then
				Me._diagnosis = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_op_name", DbType:="NVarChar(100)")>  _
	Public Property op_name() As String
		Get
			Return Me._op_name
		End Get
		Set
			If (String.Equals(Me._op_name, value) = false) Then
				Me._op_name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_loca", DbType:="NVarChar(50)")>  _
	Public Property loca() As String
		Get
			Return Me._loca
		End Get
		Set
			If (String.Equals(Me._loca, value) = false) Then
				Me._loca = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_amt", DbType:="TinyInt")>  _
	Public Property amt() As System.Nullable(Of Byte)
		Get
			Return Me._amt
		End Get
		Set
			If (Me._amt.Equals(value) = false) Then
				Me._amt = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_cloudTCM_by_uidResult
	
	Private _SDATE As Date
	
	Private _source_name As String
	
	Private _diagnosis As String
	
	Private _base As String
	
	Private _effect As String
	
	Private _dosing As String
	
	Private _days As System.Nullable(Of Byte)
	
	Private _type As String
	
	Private _amt As System.Nullable(Of Short)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date NOT NULL")>  _
	Public Property SDATE() As Date
		Get
			Return Me._SDATE
		End Get
		Set
			If ((Me._SDATE = value)  _
						= false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_source_name", DbType:="NVarChar(100)")>  _
	Public Property source_name() As String
		Get
			Return Me._source_name
		End Get
		Set
			If (String.Equals(Me._source_name, value) = false) Then
				Me._source_name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_diagnosis", DbType:="NVarChar(50)")>  _
	Public Property diagnosis() As String
		Get
			Return Me._diagnosis
		End Get
		Set
			If (String.Equals(Me._diagnosis, value) = false) Then
				Me._diagnosis = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_base", DbType:="NVarChar(50)")>  _
	Public Property base() As String
		Get
			Return Me._base
		End Get
		Set
			If (String.Equals(Me._base, value) = false) Then
				Me._base = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_effect", DbType:="NVarChar(50)")>  _
	Public Property effect() As String
		Get
			Return Me._effect
		End Get
		Set
			If (String.Equals(Me._effect, value) = false) Then
				Me._effect = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dosing", DbType:="NVarChar(50)")>  _
	Public Property dosing() As String
		Get
			Return Me._dosing
		End Get
		Set
			If (String.Equals(Me._dosing, value) = false) Then
				Me._dosing = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_days", DbType:="TinyInt")>  _
	Public Property days() As System.Nullable(Of Byte)
		Get
			Return Me._days
		End Get
		Set
			If (Me._days.Equals(value) = false) Then
				Me._days = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_type", DbType:="NVarChar(50)")>  _
	Public Property type() As String
		Get
			Return Me._type
		End Get
		Set
			If (String.Equals(Me._type, value) = false) Then
				Me._type = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_amt", DbType:="SmallInt")>  _
	Public Property amt() As System.Nullable(Of Short)
		Get
			Return Me._amt
		End Get
		Set
			If (Me._amt.Equals(value) = false) Then
				Me._amt = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_cloudREH_by_uidResult
	
	Private _SDATE As Date
	
	Private _source_name As String
	
	Private _diagnosis As String
	
	Private _type As String
	
	Private _loca As String
	
	Private _curegrade As String
	
	Private _amt As System.Nullable(Of Byte)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date NOT NULL")>  _
	Public Property SDATE() As Date
		Get
			Return Me._SDATE
		End Get
		Set
			If ((Me._SDATE = value)  _
						= false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_source_name", DbType:="NVarChar(100)")>  _
	Public Property source_name() As String
		Get
			Return Me._source_name
		End Get
		Set
			If (String.Equals(Me._source_name, value) = false) Then
				Me._source_name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_diagnosis", DbType:="NVarChar(10)")>  _
	Public Property diagnosis() As String
		Get
			Return Me._diagnosis
		End Get
		Set
			If (String.Equals(Me._diagnosis, value) = false) Then
				Me._diagnosis = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_type", DbType:="NVarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property type() As String
		Get
			Return Me._type
		End Get
		Set
			If (String.Equals(Me._type, value) = false) Then
				Me._type = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_loca", DbType:="NVarChar(50)")>  _
	Public Property loca() As String
		Get
			Return Me._loca
		End Get
		Set
			If (String.Equals(Me._loca, value) = false) Then
				Me._loca = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_curegrade", DbType:="NVarChar(50)")>  _
	Public Property curegrade() As String
		Get
			Return Me._curegrade
		End Get
		Set
			If (String.Equals(Me._curegrade, value) = false) Then
				Me._curegrade = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_amt", DbType:="TinyInt")>  _
	Public Property amt() As System.Nullable(Of Byte)
		Get
			Return Me._amt
		End Get
		Set
			If (Me._amt.Equals(value) = false) Then
				Me._amt = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_cloudDIS_by_uidResult
	
	Private _SDATE As Date
	
	Private _EDATE As Date
	
	Private _source_name As String
	
	Private _dep As String
	
	Private _diagnosis As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date NOT NULL")>  _
	Public Property SDATE() As Date
		Get
			Return Me._SDATE
		End Get
		Set
			If ((Me._SDATE = value)  _
						= false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EDATE", DbType:="Date NOT NULL")>  _
	Public Property EDATE() As Date
		Get
			Return Me._EDATE
		End Get
		Set
			If ((Me._EDATE = value)  _
						= false) Then
				Me._EDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_source_name", DbType:="NVarChar(100)")>  _
	Public Property source_name() As String
		Get
			Return Me._source_name
		End Get
		Set
			If (String.Equals(Me._source_name, value) = false) Then
				Me._source_name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dep", DbType:="NVarChar(50)")>  _
	Public Property dep() As String
		Get
			Return Me._dep
		End Get
		Set
			If (String.Equals(Me._dep, value) = false) Then
				Me._dep = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_diagnosis", DbType:="NVarChar(50)")>  _
	Public Property diagnosis() As String
		Get
			Return Me._diagnosis
		End Get
		Set
			If (String.Equals(Me._diagnosis, value) = false) Then
				Me._diagnosis = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_cloudALL_by_uidResult
	
	Private _SDATE As Date
	
	Private _source_name As String
	
	Private _remark As String
	
	Private _drug_name As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date NOT NULL")>  _
	Public Property SDATE() As Date
		Get
			Return Me._SDATE
		End Get
		Set
			If ((Me._SDATE = value)  _
						= false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_source_name", DbType:="NVarChar(100)")>  _
	Public Property source_name() As String
		Get
			Return Me._source_name
		End Get
		Set
			If (String.Equals(Me._source_name, value) = false) Then
				Me._source_name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_remark", DbType:="NVarChar(50)")>  _
	Public Property remark() As String
		Get
			Return Me._remark
		End Get
		Set
			If (String.Equals(Me._remark, value) = false) Then
				Me._remark = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_drug_name", DbType:="NVarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property drug_name() As String
		Get
			Return Me._drug_name
		End Get
		Set
			If (String.Equals(Me._drug_name, value) = false) Then
				Me._drug_name = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_cloudSCH_R_by_uidResult
	
	Private _drug_name As String
	
	Private _YM As String
	
	Private _visit_n As System.Nullable(Of Byte)
	
	Private _clinic_n As System.Nullable(Of Byte)
	
	Private _t_dose As System.Nullable(Of Short)
	
	Private _t_DDD As System.Nullable(Of Short)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_drug_name", DbType:="NVarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property drug_name() As String
		Get
			Return Me._drug_name
		End Get
		Set
			If (String.Equals(Me._drug_name, value) = false) Then
				Me._drug_name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_YM", DbType:="NVarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property YM() As String
		Get
			Return Me._YM
		End Get
		Set
			If (String.Equals(Me._YM, value) = false) Then
				Me._YM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_visit_n", DbType:="TinyInt")>  _
	Public Property visit_n() As System.Nullable(Of Byte)
		Get
			Return Me._visit_n
		End Get
		Set
			If (Me._visit_n.Equals(value) = false) Then
				Me._visit_n = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_clinic_n", DbType:="TinyInt")>  _
	Public Property clinic_n() As System.Nullable(Of Byte)
		Get
			Return Me._clinic_n
		End Get
		Set
			If (Me._clinic_n.Equals(value) = false) Then
				Me._clinic_n = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_t_dose", DbType:="SmallInt")>  _
	Public Property t_dose() As System.Nullable(Of Short)
		Get
			Return Me._t_dose
		End Get
		Set
			If (Me._t_dose.Equals(value) = false) Then
				Me._t_dose = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_t_DDD", DbType:="SmallInt")>  _
	Public Property t_DDD() As System.Nullable(Of Short)
		Get
			Return Me._t_DDD
		End Get
		Set
			If (Me._t_DDD.Equals(value) = false) Then
				Me._t_DDD = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_cloudSCH_U_by_uidResult
	
	Private _drugname As String
	
	Private _SDATE As Date
	
	Private _STIME As String
	
	Private _clinic As String
	
	Private _t_dose As System.Nullable(Of Short)
	
	Private _t_DDD As System.Nullable(Of Short)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_drugname", DbType:="NVarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property drugname() As String
		Get
			Return Me._drugname
		End Get
		Set
			If (String.Equals(Me._drugname, value) = false) Then
				Me._drugname = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SDATE", DbType:="Date NOT NULL")>  _
	Public Property SDATE() As Date
		Get
			Return Me._SDATE
		End Get
		Set
			If ((Me._SDATE = value)  _
						= false) Then
				Me._SDATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STIME", DbType:="Char(6) NOT NULL", CanBeNull:=false)>  _
	Public Property STIME() As String
		Get
			Return Me._STIME
		End Get
		Set
			If (String.Equals(Me._STIME, value) = false) Then
				Me._STIME = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_clinic", DbType:="NVarChar(10)")>  _
	Public Property clinic() As String
		Get
			Return Me._clinic
		End Get
		Set
			If (String.Equals(Me._clinic, value) = false) Then
				Me._clinic = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_t_dose", DbType:="SmallInt")>  _
	Public Property t_dose() As System.Nullable(Of Short)
		Get
			Return Me._t_dose
		End Get
		Set
			If (Me._t_dose.Equals(value) = false) Then
				Me._t_dose = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_t_DDD", DbType:="SmallInt")>  _
	Public Property t_DDD() As System.Nullable(Of Short)
		Get
			Return Me._t_DDD
		End Get
		Set
			If (Me._t_DDD.Equals(value) = false) Then
				Me._t_DDD = value
			End If
		End Set
	End Property
End Class
